services:

  # ─── RabbitMQ (Broker del microservicio) ─────────────────────────────────────
  calendario-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: calendario-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - calendario_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - calendario_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── Base de datos del microservicio ────────────────────────────────────────
  calendario-postgres:
    image: postgres:16
    container_name: calendario-postgres
    restart: always
    environment:
      POSTGRES_DB: calendario_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - calendario_net
    volumes:
      - calendario_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calendario_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ─── Microservicio Calendario de Entregas ────────────────────────────────────
  calendario-webapi:
    build:
      context: .
      dockerfile: CalendarioEntregas.WebApi/Dockerfile
    container_name: calendario-webapi
    restart: unless-stopped
    ports:
      - "7020:7020"
    depends_on:
      calendario-postgres:
        condition: service_healthy
      calendario-rabbitmq:
        condition: service_healthy
    environment:
      ConnectionStrings__CalendarioDatabase: "Host=calendario-postgres;Port=5432;Database=calendario_db;Username=postgres;Password=postgres;"
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__Host: "calendario-rabbitmq"
      RabbitMq__VirtualHost: "/"
      RabbitMq__Username: "admin"
      RabbitMq__Password: "admin"
      Jwt__Key: "DiplomadoMicroservicios2025SecretoJTWApiSecurity"
      Jwt__Issuer: "api_security"
      Jwt__Audience: "*"
    networks:
      - calendario_net

networks:
  calendario_net:
    driver: bridge
    name: calendario_net

volumes:
  calendario_pgdata:
  calendario_rabbitmq_data:
